Repository webcompat/webcompat-metrics-client, pull requests merged in 2018-12, with the labels that each got.

#111 Fixes #107 - Add weekly report module in basic form
  src/actions.js
  src/constants/ActionTypes.js
  src/containers/Navigation/__tests__/__snapshots__/Navigation-test.js.snap
  src/containers/Navigation/__tests__/__snapshots__/NavigationMatchMedia-test.js.snap
  src/containers/Navigation/index.js
  src/containers/WeeklyReports/index.js
  src/layouts/__tests__/__snapshots__/index-test.js.snap
  src/layouts/__tests__/__snapshots__/matchMedia-test.js.snap
  src/layouts/index.js
  src/modules/weeklyReports/index.js
  src/reducer.js
Labels: status: needs changes

#125 fixes #124 - fixed default path router
  webpack.config.js
Labels: status: accepted

#127 fixes #124 - handle browser history with GH pages
  src/layouts/__tests__/__snapshots__/index-test.js.snap
  src/layouts/__tests__/__snapshots__/matchMedia-test.js.snap
  src/layouts/index.js
  webpack.config.js
Labels: scope: tools, status: needs reviews

#130 Issue #128 - fixed heroku stuff
  package.json
Labels: status: accepted

#126 Fixes #121 - Add filter function to weekly reports
  src/containers/WeeklyReports/index.js
  src/layouts/__tests__/__snapshots__/index-test.js.snap
  src/layouts/__tests__/__snapshots__/matchMedia-test.js.snap
  src/modules/weeklyReports/index.js
Labels: status: accepted

#133 fixes #120 - made need diagnosis default page
  package.json
  src/containers/Navigation/__tests__/__snapshots__/Navigation-test.js.snap
  src/containers/Navigation/__tests__/__snapshots__/NavigationMatchMedia-test.js.snap
  src/containers/Navigation/index.js
  src/layouts/__tests__/__snapshots__/index-test.js.snap
  src/layouts/__tests__/__snapshots__/matchMedia-test.js.snap
  src/layouts/index.js
Labels: status: WIP
