Repository webcompat/webcompat-metrics-client, pull requests merged in 2019-03, with the labels that each got.

#151 fixes #150 - bumped packages
  .eslintrc
  package.json
  src/components/Menu/Link/__tests__/__snapshots__/Link-test.js.snap
  src/containers/Navigation/__tests__/__snapshots__/Navigation-test.js.snap
  src/containers/Navigation/__tests__/__snapshots__/NavigationMatchMedia-test.js.snap
  src/layouts/__tests__/__snapshots__/index-test.js.snap
  src/layouts/__tests__/__snapshots__/matchMedia-test.js.snap
Labels: scope : frontend, status: needs reviews

#152 fixes #149 - fixed when no date selected
  src/containers/MetricsTemplate/index.js
Labels: scope : frontend, status: needs reviews

#148 Fixes #85 - Add triage dashboard
  src/containers/Navigation/__tests__/__snapshots__/Navigation-test.js.snap
  src/containers/Navigation/__tests__/__snapshots__/NavigationMatchMedia-test.js.snap
  src/containers/Navigation/index.js
  src/containers/NeedsTriage/__tests__/NeedsTriage-test.js
  src/containers/NeedsTriage/__tests__/__snapshots__/NeedsTriage-test.js.snap
  src/containers/NeedsTriage/index.js
  src/layouts/__tests__/__snapshots__/index-test.js.snap
  src/layouts/__tests__/__snapshots__/matchMedia-test.js.snap
  src/layouts/index.js
Labels: scope : frontend, status: needs reviews

#153 Fixes #140 - Add needscontact dashboard
  package.json
  src/containers/Navigation/__tests__/__snapshots__/Navigation-test.js.snap
  src/containers/Navigation/__tests__/__snapshots__/NavigationMatchMedia-test.js.snap
  src/containers/Navigation/index.js
  src/containers/NeedsContact/__tests__/NeedsContact-test.js
  src/containers/NeedsContact/__tests__/__snapshots__/NeedsContact-test.js.snap
  src/containers/NeedsContact/index.js
  src/layouts/__tests__/__snapshots__/index-test.js.snap
  src/layouts/__tests__/__snapshots__/matchMedia-test.js.snap
  src/layouts/index.js
Labels: scope : frontend, scope: metrics, status: accepted

#155 Fixes #141 - Add sitewait dashboard
  src/containers/Navigation/__tests__/__snapshots__/Navigation-test.js.snap
  src/containers/Navigation/__tests__/__snapshots__/NavigationMatchMedia-test.js.snap
  src/containers/Navigation/index.js
  src/containers/SiteWait/__tests__/SiteWait-test.js
  src/containers/SiteWait/__tests__/__snapshots__/SiteWait-test.js.snap
  src/containers/SiteWait/index.js
  src/layouts/__tests__/__snapshots__/index-test.js.snap
  src/layouts/__tests__/__snapshots__/matchMedia-test.js.snap
  src/layouts/index.js
Labels: scope : frontend, scope: metrics, status: needs reviews
